/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fmattaperdomo.kafka.order.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CustomerAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3517976636049054878L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CustomerAvroModel\",\"namespace\":\"com.fmattaperdomo.kafka.order.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"typeIdentification\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"documentNumber\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"firstName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"lastName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"email\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"phone\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"userRole\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CustomerAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CustomerAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CustomerAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CustomerAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CustomerAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CustomerAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CustomerAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CustomerAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CustomerAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String typeIdentification;
  private java.lang.String documentNumber;
  private java.lang.String firstName;
  private java.lang.String lastName;
  private java.lang.String email;
  private java.lang.String phone;
  private java.lang.String userRole;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CustomerAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param typeIdentification The new value for typeIdentification
   * @param documentNumber The new value for documentNumber
   * @param firstName The new value for firstName
   * @param lastName The new value for lastName
   * @param email The new value for email
   * @param phone The new value for phone
   * @param userRole The new value for userRole
   */
  public CustomerAvroModel(java.lang.String id, java.lang.String typeIdentification, java.lang.String documentNumber, java.lang.String firstName, java.lang.String lastName, java.lang.String email, java.lang.String phone, java.lang.String userRole) {
    this.id = id;
    this.typeIdentification = typeIdentification;
    this.documentNumber = documentNumber;
    this.firstName = firstName;
    this.lastName = lastName;
    this.email = email;
    this.phone = phone;
    this.userRole = userRole;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return typeIdentification;
    case 2: return documentNumber;
    case 3: return firstName;
    case 4: return lastName;
    case 5: return email;
    case 6: return phone;
    case 7: return userRole;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: typeIdentification = value$ != null ? value$.toString() : null; break;
    case 2: documentNumber = value$ != null ? value$.toString() : null; break;
    case 3: firstName = value$ != null ? value$.toString() : null; break;
    case 4: lastName = value$ != null ? value$.toString() : null; break;
    case 5: email = value$ != null ? value$.toString() : null; break;
    case 6: phone = value$ != null ? value$.toString() : null; break;
    case 7: userRole = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'typeIdentification' field.
   * @return The value of the 'typeIdentification' field.
   */
  public java.lang.String getTypeIdentification() {
    return typeIdentification;
  }


  /**
   * Sets the value of the 'typeIdentification' field.
   * @param value the value to set.
   */
  public void setTypeIdentification(java.lang.String value) {
    this.typeIdentification = value;
  }

  /**
   * Gets the value of the 'documentNumber' field.
   * @return The value of the 'documentNumber' field.
   */
  public java.lang.String getDocumentNumber() {
    return documentNumber;
  }


  /**
   * Sets the value of the 'documentNumber' field.
   * @param value the value to set.
   */
  public void setDocumentNumber(java.lang.String value) {
    this.documentNumber = value;
  }

  /**
   * Gets the value of the 'firstName' field.
   * @return The value of the 'firstName' field.
   */
  public java.lang.String getFirstName() {
    return firstName;
  }


  /**
   * Sets the value of the 'firstName' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.String value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   * @return The value of the 'lastName' field.
   */
  public java.lang.String getLastName() {
    return lastName;
  }


  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.String value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.String getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.String value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'phone' field.
   * @return The value of the 'phone' field.
   */
  public java.lang.String getPhone() {
    return phone;
  }


  /**
   * Sets the value of the 'phone' field.
   * @param value the value to set.
   */
  public void setPhone(java.lang.String value) {
    this.phone = value;
  }

  /**
   * Gets the value of the 'userRole' field.
   * @return The value of the 'userRole' field.
   */
  public java.lang.String getUserRole() {
    return userRole;
  }


  /**
   * Sets the value of the 'userRole' field.
   * @param value the value to set.
   */
  public void setUserRole(java.lang.String value) {
    this.userRole = value;
  }

  /**
   * Creates a new CustomerAvroModel RecordBuilder.
   * @return A new CustomerAvroModel RecordBuilder
   */
  public static com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder newBuilder() {
    return new com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder();
  }

  /**
   * Creates a new CustomerAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CustomerAvroModel RecordBuilder
   */
  public static com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder newBuilder(com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder other) {
    if (other == null) {
      return new com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder();
    } else {
      return new com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new CustomerAvroModel RecordBuilder by copying an existing CustomerAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new CustomerAvroModel RecordBuilder
   */
  public static com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder newBuilder(com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel other) {
    if (other == null) {
      return new com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder();
    } else {
      return new com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for CustomerAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CustomerAvroModel>
    implements org.apache.avro.data.RecordBuilder<CustomerAvroModel> {

    private java.lang.String id;
    private java.lang.String typeIdentification;
    private java.lang.String documentNumber;
    private java.lang.String firstName;
    private java.lang.String lastName;
    private java.lang.String email;
    private java.lang.String phone;
    private java.lang.String userRole;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.typeIdentification)) {
        this.typeIdentification = data().deepCopy(fields()[1].schema(), other.typeIdentification);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.documentNumber)) {
        this.documentNumber = data().deepCopy(fields()[2].schema(), other.documentNumber);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.firstName)) {
        this.firstName = data().deepCopy(fields()[3].schema(), other.firstName);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.lastName)) {
        this.lastName = data().deepCopy(fields()[4].schema(), other.lastName);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.email)) {
        this.email = data().deepCopy(fields()[5].schema(), other.email);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.phone)) {
        this.phone = data().deepCopy(fields()[6].schema(), other.phone);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.userRole)) {
        this.userRole = data().deepCopy(fields()[7].schema(), other.userRole);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing CustomerAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.typeIdentification)) {
        this.typeIdentification = data().deepCopy(fields()[1].schema(), other.typeIdentification);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.documentNumber)) {
        this.documentNumber = data().deepCopy(fields()[2].schema(), other.documentNumber);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.firstName)) {
        this.firstName = data().deepCopy(fields()[3].schema(), other.firstName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.lastName)) {
        this.lastName = data().deepCopy(fields()[4].schema(), other.lastName);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.email)) {
        this.email = data().deepCopy(fields()[5].schema(), other.email);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.phone)) {
        this.phone = data().deepCopy(fields()[6].schema(), other.phone);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.userRole)) {
        this.userRole = data().deepCopy(fields()[7].schema(), other.userRole);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'typeIdentification' field.
      * @return The value.
      */
    public java.lang.String getTypeIdentification() {
      return typeIdentification;
    }


    /**
      * Sets the value of the 'typeIdentification' field.
      * @param value The value of 'typeIdentification'.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder setTypeIdentification(java.lang.String value) {
      validate(fields()[1], value);
      this.typeIdentification = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'typeIdentification' field has been set.
      * @return True if the 'typeIdentification' field has been set, false otherwise.
      */
    public boolean hasTypeIdentification() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'typeIdentification' field.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder clearTypeIdentification() {
      typeIdentification = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'documentNumber' field.
      * @return The value.
      */
    public java.lang.String getDocumentNumber() {
      return documentNumber;
    }


    /**
      * Sets the value of the 'documentNumber' field.
      * @param value The value of 'documentNumber'.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder setDocumentNumber(java.lang.String value) {
      validate(fields()[2], value);
      this.documentNumber = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'documentNumber' field has been set.
      * @return True if the 'documentNumber' field has been set, false otherwise.
      */
    public boolean hasDocumentNumber() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'documentNumber' field.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder clearDocumentNumber() {
      documentNumber = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'firstName' field.
      * @return The value.
      */
    public java.lang.String getFirstName() {
      return firstName;
    }


    /**
      * Sets the value of the 'firstName' field.
      * @param value The value of 'firstName'.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder setFirstName(java.lang.String value) {
      validate(fields()[3], value);
      this.firstName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'firstName' field has been set.
      * @return True if the 'firstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'firstName' field.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastName' field.
      * @return The value.
      */
    public java.lang.String getLastName() {
      return lastName;
    }


    /**
      * Sets the value of the 'lastName' field.
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder setLastName(java.lang.String value) {
      validate(fields()[4], value);
      this.lastName = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'lastName' field.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.String getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder setEmail(java.lang.String value) {
      validate(fields()[5], value);
      this.email = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder clearEmail() {
      email = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'phone' field.
      * @return The value.
      */
    public java.lang.String getPhone() {
      return phone;
    }


    /**
      * Sets the value of the 'phone' field.
      * @param value The value of 'phone'.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder setPhone(java.lang.String value) {
      validate(fields()[6], value);
      this.phone = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'phone' field has been set.
      * @return True if the 'phone' field has been set, false otherwise.
      */
    public boolean hasPhone() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'phone' field.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder clearPhone() {
      phone = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'userRole' field.
      * @return The value.
      */
    public java.lang.String getUserRole() {
      return userRole;
    }


    /**
      * Sets the value of the 'userRole' field.
      * @param value The value of 'userRole'.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder setUserRole(java.lang.String value) {
      validate(fields()[7], value);
      this.userRole = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'userRole' field has been set.
      * @return True if the 'userRole' field has been set, false otherwise.
      */
    public boolean hasUserRole() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'userRole' field.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerAvroModel.Builder clearUserRole() {
      userRole = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CustomerAvroModel build() {
      try {
        CustomerAvroModel record = new CustomerAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.typeIdentification = fieldSetFlags()[1] ? this.typeIdentification : (java.lang.String) defaultValue(fields()[1]);
        record.documentNumber = fieldSetFlags()[2] ? this.documentNumber : (java.lang.String) defaultValue(fields()[2]);
        record.firstName = fieldSetFlags()[3] ? this.firstName : (java.lang.String) defaultValue(fields()[3]);
        record.lastName = fieldSetFlags()[4] ? this.lastName : (java.lang.String) defaultValue(fields()[4]);
        record.email = fieldSetFlags()[5] ? this.email : (java.lang.String) defaultValue(fields()[5]);
        record.phone = fieldSetFlags()[6] ? this.phone : (java.lang.String) defaultValue(fields()[6]);
        record.userRole = fieldSetFlags()[7] ? this.userRole : (java.lang.String) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CustomerAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<CustomerAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CustomerAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<CustomerAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.typeIdentification);

    out.writeString(this.documentNumber);

    out.writeString(this.firstName);

    out.writeString(this.lastName);

    out.writeString(this.email);

    out.writeString(this.phone);

    out.writeString(this.userRole);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString();

      this.typeIdentification = in.readString();

      this.documentNumber = in.readString();

      this.firstName = in.readString();

      this.lastName = in.readString();

      this.email = in.readString();

      this.phone = in.readString();

      this.userRole = in.readString();

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString();
          break;

        case 1:
          this.typeIdentification = in.readString();
          break;

        case 2:
          this.documentNumber = in.readString();
          break;

        case 3:
          this.firstName = in.readString();
          break;

        case 4:
          this.lastName = in.readString();
          break;

        case 5:
          this.email = in.readString();
          break;

        case 6:
          this.phone = in.readString();
          break;

        case 7:
          this.userRole = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










