/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fmattaperdomo.kafka.order.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CustomerDocument extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1306368378942336169L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CustomerDocument\",\"namespace\":\"com.fmattaperdomo.kafka.order.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"logicalType\":\"uuid\"},{\"name\":\"typeIdentification\",\"type\":{\"type\":\"enum\",\"name\":\"TypeIdentification\",\"symbols\":[\"DNI\",\"CITIZENSHIP\",\"PASSPORT\",\"IDENTITY\",\"OTHER\"]}},{\"name\":\"documentNumber\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CustomerDocument> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CustomerDocument> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CustomerDocument> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CustomerDocument> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CustomerDocument> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CustomerDocument to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CustomerDocument from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CustomerDocument instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CustomerDocument fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private com.fmattaperdomo.kafka.order.avro.model.TypeIdentification typeIdentification;
  private java.lang.String documentNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CustomerDocument() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param typeIdentification The new value for typeIdentification
   * @param documentNumber The new value for documentNumber
   */
  public CustomerDocument(java.lang.String id, com.fmattaperdomo.kafka.order.avro.model.TypeIdentification typeIdentification, java.lang.String documentNumber) {
    this.id = id;
    this.typeIdentification = typeIdentification;
    this.documentNumber = documentNumber;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return typeIdentification;
    case 2: return documentNumber;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: typeIdentification = (com.fmattaperdomo.kafka.order.avro.model.TypeIdentification)value$; break;
    case 2: documentNumber = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'typeIdentification' field.
   * @return The value of the 'typeIdentification' field.
   */
  public com.fmattaperdomo.kafka.order.avro.model.TypeIdentification getTypeIdentification() {
    return typeIdentification;
  }


  /**
   * Sets the value of the 'typeIdentification' field.
   * @param value the value to set.
   */
  public void setTypeIdentification(com.fmattaperdomo.kafka.order.avro.model.TypeIdentification value) {
    this.typeIdentification = value;
  }

  /**
   * Gets the value of the 'documentNumber' field.
   * @return The value of the 'documentNumber' field.
   */
  public java.lang.String getDocumentNumber() {
    return documentNumber;
  }


  /**
   * Sets the value of the 'documentNumber' field.
   * @param value the value to set.
   */
  public void setDocumentNumber(java.lang.String value) {
    this.documentNumber = value;
  }

  /**
   * Creates a new CustomerDocument RecordBuilder.
   * @return A new CustomerDocument RecordBuilder
   */
  public static com.fmattaperdomo.kafka.order.avro.model.CustomerDocument.Builder newBuilder() {
    return new com.fmattaperdomo.kafka.order.avro.model.CustomerDocument.Builder();
  }

  /**
   * Creates a new CustomerDocument RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CustomerDocument RecordBuilder
   */
  public static com.fmattaperdomo.kafka.order.avro.model.CustomerDocument.Builder newBuilder(com.fmattaperdomo.kafka.order.avro.model.CustomerDocument.Builder other) {
    if (other == null) {
      return new com.fmattaperdomo.kafka.order.avro.model.CustomerDocument.Builder();
    } else {
      return new com.fmattaperdomo.kafka.order.avro.model.CustomerDocument.Builder(other);
    }
  }

  /**
   * Creates a new CustomerDocument RecordBuilder by copying an existing CustomerDocument instance.
   * @param other The existing instance to copy.
   * @return A new CustomerDocument RecordBuilder
   */
  public static com.fmattaperdomo.kafka.order.avro.model.CustomerDocument.Builder newBuilder(com.fmattaperdomo.kafka.order.avro.model.CustomerDocument other) {
    if (other == null) {
      return new com.fmattaperdomo.kafka.order.avro.model.CustomerDocument.Builder();
    } else {
      return new com.fmattaperdomo.kafka.order.avro.model.CustomerDocument.Builder(other);
    }
  }

  /**
   * RecordBuilder for CustomerDocument instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CustomerDocument>
    implements org.apache.avro.data.RecordBuilder<CustomerDocument> {

    private java.lang.String id;
    private com.fmattaperdomo.kafka.order.avro.model.TypeIdentification typeIdentification;
    private java.lang.String documentNumber;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.fmattaperdomo.kafka.order.avro.model.CustomerDocument.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.typeIdentification)) {
        this.typeIdentification = data().deepCopy(fields()[1].schema(), other.typeIdentification);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.documentNumber)) {
        this.documentNumber = data().deepCopy(fields()[2].schema(), other.documentNumber);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing CustomerDocument instance
     * @param other The existing instance to copy.
     */
    private Builder(com.fmattaperdomo.kafka.order.avro.model.CustomerDocument other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.typeIdentification)) {
        this.typeIdentification = data().deepCopy(fields()[1].schema(), other.typeIdentification);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.documentNumber)) {
        this.documentNumber = data().deepCopy(fields()[2].schema(), other.documentNumber);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerDocument.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerDocument.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'typeIdentification' field.
      * @return The value.
      */
    public com.fmattaperdomo.kafka.order.avro.model.TypeIdentification getTypeIdentification() {
      return typeIdentification;
    }


    /**
      * Sets the value of the 'typeIdentification' field.
      * @param value The value of 'typeIdentification'.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerDocument.Builder setTypeIdentification(com.fmattaperdomo.kafka.order.avro.model.TypeIdentification value) {
      validate(fields()[1], value);
      this.typeIdentification = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'typeIdentification' field has been set.
      * @return True if the 'typeIdentification' field has been set, false otherwise.
      */
    public boolean hasTypeIdentification() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'typeIdentification' field.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerDocument.Builder clearTypeIdentification() {
      typeIdentification = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'documentNumber' field.
      * @return The value.
      */
    public java.lang.String getDocumentNumber() {
      return documentNumber;
    }


    /**
      * Sets the value of the 'documentNumber' field.
      * @param value The value of 'documentNumber'.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerDocument.Builder setDocumentNumber(java.lang.String value) {
      validate(fields()[2], value);
      this.documentNumber = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'documentNumber' field has been set.
      * @return True if the 'documentNumber' field has been set, false otherwise.
      */
    public boolean hasDocumentNumber() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'documentNumber' field.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.CustomerDocument.Builder clearDocumentNumber() {
      documentNumber = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CustomerDocument build() {
      try {
        CustomerDocument record = new CustomerDocument();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.typeIdentification = fieldSetFlags()[1] ? this.typeIdentification : (com.fmattaperdomo.kafka.order.avro.model.TypeIdentification) defaultValue(fields()[1]);
        record.documentNumber = fieldSetFlags()[2] ? this.documentNumber : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CustomerDocument>
    WRITER$ = (org.apache.avro.io.DatumWriter<CustomerDocument>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CustomerDocument>
    READER$ = (org.apache.avro.io.DatumReader<CustomerDocument>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeEnum(this.typeIdentification.ordinal());

    out.writeString(this.documentNumber);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString();

      this.typeIdentification = com.fmattaperdomo.kafka.order.avro.model.TypeIdentification.values()[in.readEnum()];

      this.documentNumber = in.readString();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString();
          break;

        case 1:
          this.typeIdentification = com.fmattaperdomo.kafka.order.avro.model.TypeIdentification.values()[in.readEnum()];
          break;

        case 2:
          this.documentNumber = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










