/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fmattaperdomo.kafka.order.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProductFeature extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8658371893673533456L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductFeature\",\"namespace\":\"com.fmattaperdomo.kafka.order.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"logicalType\":\"uuid\"},{\"name\":\"productId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"logicalType\":\"uuid\"},{\"name\":\"feature\",\"type\":{\"type\":\"record\",\"name\":\"Feature\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"logicalType\":\"uuid\"},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}},{\"name\":\"value\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"updatedAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<ProductFeature> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductFeature> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductFeature> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductFeature> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductFeature> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductFeature to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductFeature from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductFeature instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductFeature fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String productId;
  private com.fmattaperdomo.kafka.order.avro.model.Feature feature;
  private java.lang.String value;
  private java.time.Instant createdAt;
  private java.time.Instant updatedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductFeature() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param productId The new value for productId
   * @param feature The new value for feature
   * @param value The new value for value
   * @param createdAt The new value for createdAt
   * @param updatedAt The new value for updatedAt
   */
  public ProductFeature(java.lang.String id, java.lang.String productId, com.fmattaperdomo.kafka.order.avro.model.Feature feature, java.lang.String value, java.time.Instant createdAt, java.time.Instant updatedAt) {
    this.id = id;
    this.productId = productId;
    this.feature = feature;
    this.value = value;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.updatedAt = updatedAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return productId;
    case 2: return feature;
    case 3: return value;
    case 4: return createdAt;
    case 5: return updatedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: productId = value$ != null ? value$.toString() : null; break;
    case 2: feature = (com.fmattaperdomo.kafka.order.avro.model.Feature)value$; break;
    case 3: value = value$ != null ? value$.toString() : null; break;
    case 4: createdAt = (java.time.Instant)value$; break;
    case 5: updatedAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'productId' field.
   * @return The value of the 'productId' field.
   */
  public java.lang.String getProductId() {
    return productId;
  }


  /**
   * Sets the value of the 'productId' field.
   * @param value the value to set.
   */
  public void setProductId(java.lang.String value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'feature' field.
   * @return The value of the 'feature' field.
   */
  public com.fmattaperdomo.kafka.order.avro.model.Feature getFeature() {
    return feature;
  }


  /**
   * Sets the value of the 'feature' field.
   * @param value the value to set.
   */
  public void setFeature(com.fmattaperdomo.kafka.order.avro.model.Feature value) {
    this.feature = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.lang.String getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.String value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'updatedAt' field.
   * @return The value of the 'updatedAt' field.
   */
  public java.time.Instant getUpdatedAt() {
    return updatedAt;
  }


  /**
   * Sets the value of the 'updatedAt' field.
   * @param value the value to set.
   */
  public void setUpdatedAt(java.time.Instant value) {
    this.updatedAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new ProductFeature RecordBuilder.
   * @return A new ProductFeature RecordBuilder
   */
  public static com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder newBuilder() {
    return new com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder();
  }

  /**
   * Creates a new ProductFeature RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductFeature RecordBuilder
   */
  public static com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder newBuilder(com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder other) {
    if (other == null) {
      return new com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder();
    } else {
      return new com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder(other);
    }
  }

  /**
   * Creates a new ProductFeature RecordBuilder by copying an existing ProductFeature instance.
   * @param other The existing instance to copy.
   * @return A new ProductFeature RecordBuilder
   */
  public static com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder newBuilder(com.fmattaperdomo.kafka.order.avro.model.ProductFeature other) {
    if (other == null) {
      return new com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder();
    } else {
      return new com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductFeature instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductFeature>
    implements org.apache.avro.data.RecordBuilder<ProductFeature> {

    private java.lang.String id;
    private java.lang.String productId;
    private com.fmattaperdomo.kafka.order.avro.model.Feature feature;
    private com.fmattaperdomo.kafka.order.avro.model.Feature.Builder featureBuilder;
    private java.lang.String value;
    private java.time.Instant createdAt;
    private java.time.Instant updatedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.feature)) {
        this.feature = data().deepCopy(fields()[2].schema(), other.feature);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasFeatureBuilder()) {
        this.featureBuilder = com.fmattaperdomo.kafka.order.avro.model.Feature.newBuilder(other.getFeatureBuilder());
      }
      if (isValidValue(fields()[3], other.value)) {
        this.value = data().deepCopy(fields()[3].schema(), other.value);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[4].schema(), other.createdAt);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[5].schema(), other.updatedAt);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing ProductFeature instance
     * @param other The existing instance to copy.
     */
    private Builder(com.fmattaperdomo.kafka.order.avro.model.ProductFeature other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.feature)) {
        this.feature = data().deepCopy(fields()[2].schema(), other.feature);
        fieldSetFlags()[2] = true;
      }
      this.featureBuilder = null;
      if (isValidValue(fields()[3], other.value)) {
        this.value = data().deepCopy(fields()[3].schema(), other.value);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[4].schema(), other.createdAt);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[5].schema(), other.updatedAt);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'productId' field.
      * @return The value.
      */
    public java.lang.String getProductId() {
      return productId;
    }


    /**
      * Sets the value of the 'productId' field.
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder setProductId(java.lang.String value) {
      validate(fields()[1], value);
      this.productId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'productId' field.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder clearProductId() {
      productId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'feature' field.
      * @return The value.
      */
    public com.fmattaperdomo.kafka.order.avro.model.Feature getFeature() {
      return feature;
    }


    /**
      * Sets the value of the 'feature' field.
      * @param value The value of 'feature'.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder setFeature(com.fmattaperdomo.kafka.order.avro.model.Feature value) {
      validate(fields()[2], value);
      this.featureBuilder = null;
      this.feature = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'feature' field has been set.
      * @return True if the 'feature' field has been set, false otherwise.
      */
    public boolean hasFeature() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'feature' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.fmattaperdomo.kafka.order.avro.model.Feature.Builder getFeatureBuilder() {
      if (featureBuilder == null) {
        if (hasFeature()) {
          setFeatureBuilder(com.fmattaperdomo.kafka.order.avro.model.Feature.newBuilder(feature));
        } else {
          setFeatureBuilder(com.fmattaperdomo.kafka.order.avro.model.Feature.newBuilder());
        }
      }
      return featureBuilder;
    }

    /**
     * Sets the Builder instance for the 'feature' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder setFeatureBuilder(com.fmattaperdomo.kafka.order.avro.model.Feature.Builder value) {
      clearFeature();
      featureBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'feature' field has an active Builder instance
     * @return True if the 'feature' field has an active Builder instance
     */
    public boolean hasFeatureBuilder() {
      return featureBuilder != null;
    }

    /**
      * Clears the value of the 'feature' field.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder clearFeature() {
      feature = null;
      featureBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.String getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder setValue(java.lang.String value) {
      validate(fields()[3], value);
      this.value = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder clearValue() {
      value = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[4], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder clearCreatedAt() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'updatedAt' field.
      * @return The value.
      */
    public java.time.Instant getUpdatedAt() {
      return updatedAt;
    }


    /**
      * Sets the value of the 'updatedAt' field.
      * @param value The value of 'updatedAt'.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder setUpdatedAt(java.time.Instant value) {
      validate(fields()[5], value);
      this.updatedAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'updatedAt' field has been set.
      * @return True if the 'updatedAt' field has been set, false otherwise.
      */
    public boolean hasUpdatedAt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'updatedAt' field.
      * @return This builder.
      */
    public com.fmattaperdomo.kafka.order.avro.model.ProductFeature.Builder clearUpdatedAt() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductFeature build() {
      try {
        ProductFeature record = new ProductFeature();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.productId = fieldSetFlags()[1] ? this.productId : (java.lang.String) defaultValue(fields()[1]);
        if (featureBuilder != null) {
          try {
            record.feature = this.featureBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("feature"));
            throw e;
          }
        } else {
          record.feature = fieldSetFlags()[2] ? this.feature : (com.fmattaperdomo.kafka.order.avro.model.Feature) defaultValue(fields()[2]);
        }
        record.value = fieldSetFlags()[3] ? this.value : (java.lang.String) defaultValue(fields()[3]);
        record.createdAt = fieldSetFlags()[4] ? this.createdAt : (java.time.Instant) defaultValue(fields()[4]);
        record.updatedAt = fieldSetFlags()[5] ? this.updatedAt : (java.time.Instant) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductFeature>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductFeature>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductFeature>
    READER$ = (org.apache.avro.io.DatumReader<ProductFeature>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










