/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fmattaperdomo.kafka.order.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum TypeIdentification implements org.apache.avro.generic.GenericEnumSymbol<TypeIdentification> {
  DNI, CITIZENSHIP, PASSPORT, IDENTITY, OTHER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TypeIdentification\",\"namespace\":\"com.fmattaperdomo.kafka.order.avro.model\",\"symbols\":[\"DNI\",\"CITIZENSHIP\",\"PASSPORT\",\"IDENTITY\",\"OTHER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
