/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fmattaperdomo.kafka.order.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum UserRole implements org.apache.avro.generic.GenericEnumSymbol<UserRole> {
  CUSTOMER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UserRole\",\"namespace\":\"com.fmattaperdomo.kafka.order.avro.model\",\"symbols\":[\"CUSTOMER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
