---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-arka-project-kafka
  labels:
    
    ecommerce-arka-project.io/name: ecommerce-arka-project-kafka
    app.kubernetes.io/instance: ecommerce-arka-project
    app.kubernetes.io/component: kafka
    app.kubernetes.io/name: ecommerce-arka-project-kafka
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/part-of: ecommerce-arka-project
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      
      ecommerce-arka-project.io/name: ecommerce-arka-project-kafka
  template:
    metadata:
      labels:
        
        ecommerce-arka-project.io/name: ecommerce-arka-project-kafka
        app.kubernetes.io/instance: ecommerce-arka-project
        app.kubernetes.io/component: kafka
        app.kubernetes.io/name: ecommerce-arka-project-kafka
    spec:
      serviceAccountName: ecommerce-arka-project
      containers:
        - name: kafka
          image: 'fmattaperdomo/ecommerce-arka-project:1.12.0-kafka'
          imagePullPolicy: IfNotPresent
          ports:
            
            - containerPort: 9092
              name: plaintext
            - containerPort: 9093
              name: controller
          env:
            - name: EAP_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app.kubernetes.io/component']
            - name: EAP_COLLECTOR_NAME
              value: 'ecommerce-arka-project-otelcol'
            - name: EAP_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: cumulative
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://ecommerce-arka-project-kafka:9092
            - name: EAP_EXPORTER_OTLP_ENDPOINT
              value: http://$(EAP_COLLECTOR_NAME):4318
            - name: KAFKA_HEAP_OPTS
              value: -Xmx400M -Xms400M
            - name: EAP_RESOURCE_ATTRIBUTES
              value: service.name=$(EAP_SERVICE_NAME),service.namespace=ecommerce-arka-project,service.version=1.12.0
          resources:
            limits:
              memory: 600Mi
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
      volumes:
